# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: List.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Attribute_pb2 as Attribute__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nList.proto\x12\rattrpubapi_v1\x1a\x0f\x41ttribute.proto\"S\n\x0e\x41ttributeAndId\x12+\n\tattribute\x18\x01 \x01(\x0b\x32\x18.attrpubapi_v1.Attribute\x12\x14\n\x0c\x61ttribute_id\x18\x02 \x01(\x0c\"R\n\x12\x41ttributeAndIdList\x12<\n\x15\x61ttribute_and_id_list\x18\x01 \x03(\x0b\x32\x1d.attrpubapi_v1.AttributeAndId\"=\n\rAttributeList\x12,\n\nattributes\x18\x01 \x03(\x0b\x32\x18.attrpubapi_v1.Attributeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'List_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ATTRIBUTEANDID']._serialized_start=46
  _globals['_ATTRIBUTEANDID']._serialized_end=129
  _globals['_ATTRIBUTEANDIDLIST']._serialized_start=131
  _globals['_ATTRIBUTEANDIDLIST']._serialized_end=213
  _globals['_ATTRIBUTELIST']._serialized_start=215
  _globals['_ATTRIBUTELIST']._serialized_end=276
# @@protoc_insertion_point(module_scope)
