# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExtraData.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DataEntry_pb2 as DataEntry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x45xtraData.proto\x12\x0esharepubapi_v1\x1a\x0f\x44\x61taEntry.proto\"4\n\tExtraData\x12\'\n\x04list\x18\x01 \x03(\x0b\x32\x19.sharepubapi_v1.DataEntryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ExtraData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXTRADATA']._serialized_start=52
  _globals['_EXTRADATA']._serialized_end=104
# @@protoc_insertion_point(module_scope)
