# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExtraData.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DataEntry_pb2 as DataEntry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ExtraData.proto',
  package='sharepubapi_v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x45xtraData.proto\x12\x0esharepubapi_v1\x1a\x0f\x44\x61taEntry.proto\"4\n\tExtraData\x12\'\n\x04list\x18\x01 \x03(\x0b\x32\x19.sharepubapi_v1.DataEntryb\x06proto3'
  ,
  dependencies=[DataEntry__pb2.DESCRIPTOR,])




_EXTRADATA = _descriptor.Descriptor(
  name='ExtraData',
  full_name='sharepubapi_v1.ExtraData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='sharepubapi_v1.ExtraData.list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=104,
)

_EXTRADATA.fields_by_name['list'].message_type = DataEntry__pb2._DATAENTRY
DESCRIPTOR.message_types_by_name['ExtraData'] = _EXTRADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExtraData = _reflection.GeneratedProtocolMessageType('ExtraData', (_message.Message,), {
  'DESCRIPTOR' : _EXTRADATA,
  '__module__' : 'ExtraData_pb2'
  # @@protoc_insertion_point(class_scope:sharepubapi_v1.ExtraData)
  })
_sym_db.RegisterMessage(ExtraData)


# @@protoc_insertion_point(module_scope)
