# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IssuingAttributes.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='IssuingAttributes.proto',
  package='sharepubapi_v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17IssuingAttributes.proto\x12\x0esharepubapi_v1\"Y\n\x11IssuingAttributes\x12\x13\n\x0b\x65xpiry_date\x18\x01 \x01(\t\x12/\n\x0b\x64\x65\x66initions\x18\x02 \x03(\x0b\x32\x1a.sharepubapi_v1.Definition\"\x1a\n\nDefinition\x12\x0c\n\x04name\x18\x01 \x01(\tb\x06proto3'
)




_ISSUINGATTRIBUTES = _descriptor.Descriptor(
  name='IssuingAttributes',
  full_name='sharepubapi_v1.IssuingAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='expiry_date', full_name='sharepubapi_v1.IssuingAttributes.expiry_date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='definitions', full_name='sharepubapi_v1.IssuingAttributes.definitions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=132,
)


_DEFINITION = _descriptor.Descriptor(
  name='Definition',
  full_name='sharepubapi_v1.Definition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='sharepubapi_v1.Definition.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=160,
)

_ISSUINGATTRIBUTES.fields_by_name['definitions'].message_type = _DEFINITION
DESCRIPTOR.message_types_by_name['IssuingAttributes'] = _ISSUINGATTRIBUTES
DESCRIPTOR.message_types_by_name['Definition'] = _DEFINITION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IssuingAttributes = _reflection.GeneratedProtocolMessageType('IssuingAttributes', (_message.Message,), {
  'DESCRIPTOR' : _ISSUINGATTRIBUTES,
  '__module__' : 'IssuingAttributes_pb2'
  # @@protoc_insertion_point(class_scope:sharepubapi_v1.IssuingAttributes)
  })
_sym_db.RegisterMessage(IssuingAttributes)

Definition = _reflection.GeneratedProtocolMessageType('Definition', (_message.Message,), {
  'DESCRIPTOR' : _DEFINITION,
  '__module__' : 'IssuingAttributes_pb2'
  # @@protoc_insertion_point(class_scope:sharepubapi_v1.Definition)
  })
_sym_db.RegisterMessage(Definition)


# @@protoc_insertion_point(module_scope)
