# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThirdPartyAttribute.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IssuingAttributes_pb2 as IssuingAttributes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19ThirdPartyAttribute.proto\x12\x0esharepubapi_v1\x1a\x17IssuingAttributes.proto\"l\n\x13ThirdPartyAttribute\x12\x16\n\x0eissuance_token\x18\x01 \x01(\x0c\x12=\n\x12issuing_attributes\x18\x02 \x01(\x0b\x32!.sharepubapi_v1.IssuingAttributesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ThirdPartyAttribute_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_THIRDPARTYATTRIBUTE']._serialized_start=70
  _globals['_THIRDPARTYATTRIBUTE']._serialized_end=178
# @@protoc_insertion_point(module_scope)
